#!/usr/bin/env python3
"""Demo script for testing the Twisted version of the EmbeddedHealthHostInjector"""
import logging
from twisted.python import log
from twisted.internet import reactor
from txjsonrpcqueue.steem import EmbeddedHealthHostInjector

class InjectLogger(object):
    #pylint: disable=too-few-public-methods
    """Class that only logs what gets injected."""
    def __init__(self, start_node):
        self.injector = EmbeddedHealthHostInjector(start_node)
        self.injector.register_forwarder(self)
        self.fastest_node = start_node
    def inject_host_url(self, url):
        """Entry point for EmbeddedHealthHostInjector events"""
        self.fastest_node = url
        log.msg("New fastest node:" + url)

log.PythonLoggingObserver().start()
logging.basicConfig(filename="test-twisted-injector.log", level=logging.DEBUG)

FR = InjectLogger("https://api.steemit.com")
print("Logs will go to: test-twisted-injector.log")
#pylint: disable=no-member
reactor.run()
